# Generated by Django 4.1.7 on 2023-03-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='importance',
            new_name='priority',
        ),
    ]
