# Generated by Django 4.1.7 on 2023-03-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasonstodecline',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
