# Generated by Django 4.1.7 on 2023-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_reasonstodecline_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_reclaimed',
            field=models.BooleanField(default=False),
        ),
    ]
