# Generated by Django 4.1.7 on 2023-03-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_is_reclaimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_finally_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_of_comment',
            field=models.TextField(verbose_name='Your comment'),
        ),
    ]
